### ISSUE TITLE
Autotick bot did not kicked in for v0.7.0

### ISSUE THREAD

**Issue by sdebionne** [conda-forge/sphinxcontrib-mermaid-feedstock#5]
- [ ] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

Recipe should be re-rendered for v0.7.0

**Comment by ericpre** [comment]
Indeed, thanks! Do you want to make a PR to update the recipe?

**Comment by sdebionne** [comment]
Done. I had to switch source from `https://pypi.io/packages/source` to github, is that OK for you?

**Comment by ericpre** [comment]
As far as I know, the pypi tarball are preferred over github - the reason _may be_ that the github tarball can changed while the pypi one can't?!
Do you have a reason to use github over pypi?
